services:
  # Presentation Layer
  frontend:
    build: ./presentation
    container_name: frontend
    ports:
      - "80:80"
  # Business Layer
  locationservice:
    build: ./business/locationService
    container_name: "locationservice"
    ports:
      - "81:81"
  testdriveservice:
    build: ./business/testdriveService
    container_name: "testdriveservice"
    ports:
      - "82:82"
  shoppingcartservice:
    build: ./business/shoppingcartService
    container_name: shoppingcartservice
    ports:
      - "83:83"
  merchitemsservice:
    build: ./business/merchItemsService
    container_name: "merchitemsservice"
    ports:
      - "85:85"
  configuratorservice:
    build: ./business/configuratorService
    container_name: "configuratorservice"
    ports:
      - "86:86"  
  # Data Layer
  minio:
    image: docker.io/minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './data/minio/data:/data'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=hotel
    command: server /export --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
  car_db:
    container_name: car_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: merchandise_db
      MYSQL_USER: hhz
      MYSQL_PASSWORD: car
    volumes:
      - ./data/webshop_datenbank/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  minio_data:
  redis-data: